use std::{
    env, fs,
    path::{Path, PathBuf},
};

/// Scans `skills_dir` for subdirectories that contain a `SKILL.md` file.
/// The subdirectory name is used as the skill name (matches agentskills.io spec).
/// If a `persona_config.json` exists alongside `SKILL.md`, it is embedded as `config`.
fn generate_skills_registry(skills_dir: &Path) -> String {
    let mut entries = Vec::new();

    if let Ok(read_dir) = fs::read_dir(skills_dir) {
        let mut dirs: Vec<PathBuf> = read_dir
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        dirs.sort(); // deterministic order

        for dir in &dirs {
            let skill_md = dir.join("SKILL.md");
            if skill_md.exists() {
                let abs = fs::canonicalize(&skill_md).unwrap();
                let name = dir.file_name().unwrap().to_str().unwrap().to_owned();
                println!("cargo:rerun-if-changed={}", abs.display());

                let config_path = dir.join("persona_config.json");
                let config_abs = if config_path.exists() {
                    let abs_cfg = fs::canonicalize(&config_path).unwrap();
                    println!("cargo:rerun-if-changed={}", abs_cfg.display());
                    Some(abs_cfg)
                } else {
                    None
                };

                entries.push((name, abs, config_abs));
            }
        }
    }

    // Re-run if a skill directory is added or removed
    println!("cargo:rerun-if-changed={}", skills_dir.display());

    let items: Vec<String> = entries
        .iter()
        .map(|(name, path, config)| {
            let config_field = match config {
                Some(cfg_path) => format!("Some(include_str!({:?}))", cfg_path),
                None => "None".to_string(),
            };
            format!(
                r#"    Skill {{ name: {:?}, content: include_str!({:?}), config: {config_field} }}"#,
                name,
                path,
            )
        })
        .collect();

    items.join(",\n")
}

/// Scans `tools_dir` for `.json` tool schema files.
fn generate_tools_registry(tools_dir: &Path) -> String {
    let mut entries = Vec::new();

    if let Ok(read_dir) = fs::read_dir(tools_dir) {
        let mut paths: Vec<PathBuf> = read_dir
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("json"))
            .collect();
        paths.sort();

        for path in &paths {
            let abs = fs::canonicalize(path).unwrap();
            let name = path.file_stem().unwrap().to_str().unwrap().to_owned();
            println!("cargo:rerun-if-changed={}", abs.display());
            entries.push((name, abs));
        }
    }

    println!("cargo:rerun-if-changed={}", tools_dir.display());

    let items: Vec<String> = entries
        .iter()
        .map(|(name, path)| {
            format!(
                r#"    Tool {{ name: {:?}, content: include_str!({:?}) }}"#,
                name,
                path,
            )
        })
        .collect();

    items.join(",\n")
}

fn main() {
    tauri_build::build();

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let skills_dir = Path::new(&manifest_dir).join("src").join("skills");
    let tools_dir = Path::new(&manifest_dir).join("src").join("tools").join("regtools");

    let skills_items = generate_skills_registry(&skills_dir);
    let tools_items = generate_tools_registry(&tools_dir);

    let generated = format!(
        r#"// Auto-generated by build.rs — do not edit manually.
// Add/remove files in src-tauri/src/skills/ or src-tauri/src/tools/regtools/ and rebuild.

#[allow(dead_code)]
pub struct Skill {{
    pub name: &'static str,
    pub content: &'static str,
    /// Embedded persona_config.json, if present alongside SKILL.md.
    pub config: Option<&'static str>,
}}

#[allow(dead_code)]
pub struct Tool {{
    pub name: &'static str,
    pub content: &'static str,
}}

pub static SKILLS: &[Skill] = &[
{skills}
];

pub static TOOLS: &[Tool] = &[
{tools}
];
"#,
        skills = skills_items,
        tools = tools_items,
    );

    fs::write(out_dir.join("agent_registry.rs"), generated).unwrap();
}

