/// Character memory: brief summaries of past posts and comments with importance scoring.
///
/// Each entry has:
/// - `importance` (1–10): entries with importance > 8 are "permanent" (never forgotten).
///   Entries with importance <= 8 are forgotten when their age exceeds FORGET_AFTER_DAYS.
/// - `brief`: a short 1–2 sentence summary of what was posted/commented.
/// - `entry_type`: "post" or "comment"
/// - `character_id`: owner of this memory
/// - `created_at`: Unix timestamp (seconds)
///
/// Storage: one JSON array per character at
///   {app_data}/memory/character_memory/{character_id}.json
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use tauri::AppHandle;

use crate::chat::memory_dir;

const FORGET_AFTER_DAYS: u64 = 20;
const FORGET_THRESHOLD: u8 = 80; // importance < this can be forgotten (≥80 = permanent)

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum MemoryEntryType {
    Post,
    Comment,
    Conversation,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct MemoryEntry {
    pub id: String,
    pub character_id: String,
    pub entry_type: MemoryEntryType,
    /// Brief 1-2 sentence summary generated by LLM.
    pub brief: String,
    /// Importance score 1–10. >8 = permanent; <=8 = forgotten after FORGET_AFTER_DAYS.
    pub importance: u8,
    /// Unix timestamp (seconds).
    pub created_at: u64,
}

// ── Path helpers ──────────────────────────────────────────────────────────────

fn memory_dir_path(app: &AppHandle) -> PathBuf {
    memory_dir(app).join("character_memory")
}

fn character_memory_path(app: &AppHandle, character_id: &str) -> PathBuf {
    memory_dir_path(app).join(format!("{character_id}.json"))
}

fn now_secs() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

// ── Read / Write ──────────────────────────────────────────────────────────────

fn load_raw(app: &AppHandle, character_id: &str) -> Vec<MemoryEntry> {
    let path = character_memory_path(app, character_id);
    let text = std::fs::read_to_string(&path).unwrap_or_default();
    serde_json::from_str(&text).unwrap_or_default()
}

fn save_all(app: &AppHandle, character_id: &str, entries: &[MemoryEntry]) -> Result<(), String> {
    let dir = memory_dir_path(app);
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let json = serde_json::to_string(entries).map_err(|e| e.to_string())?;
    std::fs::write(character_memory_path(app, character_id), json).map_err(|e| e.to_string())
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Return all active (non-forgotten) memories for a character, newest first.
/// Permanent entries (importance >= 80) are always included.
/// Entries with importance < 80 are dropped if older than FORGET_AFTER_DAYS.
pub fn load_active(app: &AppHandle, character_id: &str) -> Vec<MemoryEntry> {
    let now = now_secs();
    let forget_secs = FORGET_AFTER_DAYS * 86_400;
    load_raw(app, character_id)
        .into_iter()
        .filter(|e| {
            if e.importance >= FORGET_THRESHOLD {
                true // permanent
            } else {
                now.saturating_sub(e.created_at) < forget_secs
            }
        })
        .collect()
}

/// Append a new memory entry for a character.
pub fn add_entry(app: &AppHandle, entry: MemoryEntry) -> Result<(), String> {
    let mut entries = load_raw(app, &entry.character_id.clone());
    entries.push(entry.clone());
    // Prune forgotten entries while we're here to keep the file lean
    let now = now_secs();
    let forget_secs = FORGET_AFTER_DAYS * 86_400;
    entries.retain(|e| {
        e.importance >= FORGET_THRESHOLD || now.saturating_sub(e.created_at) < forget_secs
    });
    save_all(app, &entry.character_id, &entries)
}

/// Build a compact context block of past memories to inject into a prompt.
/// Returns an empty string if there are no active memories.
pub fn build_memory_context(app: &AppHandle, character_id: &str) -> String {
    let entries = load_active(app, character_id);
    if entries.is_empty() {
        return String::new();
    }
    // Sort: permanent entries first (importance ≥ 80), then recency.
    let mut sorted: Vec<&MemoryEntry> = entries.iter().collect();
    sorted.sort_by(|a, b| {
        let a_perm = a.importance >= FORGET_THRESHOLD;
        let b_perm = b.importance >= FORGET_THRESHOLD;
        b_perm.cmp(&a_perm).then(b.created_at.cmp(&a.created_at))
    });

    let mut lines = String::from("[YOUR PAST ACTIVITY]\nBrief summaries of your recent posts, comments, and conversations. Stay consistent with your past self:\n");
    let mut total_chars = 0usize;
    const MAX_CHARS: usize = 3000;

    for e in &sorted {
        let kind = match e.entry_type {
            MemoryEntryType::Post => "Posted",
            MemoryEntryType::Comment => "Commented",
            MemoryEntryType::Conversation => "Said to user",
        };
        let line = format!("- {kind}: {}\n", e.brief);
        if total_chars + line.len() > MAX_CHARS { break; }
        total_chars += line.len();
        lines.push_str(&line);
    }
    lines
}

/// Helper: current unix timestamp (seconds).
pub fn current_ts() -> u64 {
    now_secs()
}
