use tauri::AppHandle;

use super::store;
use super::types::{PairedDevice, PcPermissions, SessionConfig};

/// Return the current session config (creates default on first run).
#[tauri::command]
pub fn get_session(app: AppHandle) -> Result<SessionConfig, String> {
    Ok(store::bootstrap(&app))
}

/// Set a human-readable label for this device (e.g. "My Phone").
#[tauri::command]
pub fn set_device_label(app: AppHandle, label: String) -> Result<SessionConfig, String> {
    store::set_label(&app, &label)
}

/// Set the session hash key directly.
/// Only accepts the 64-character hex key generated by the app.
#[tauri::command]
pub fn set_session_hash_key(app: AppHandle, hash_key: String) -> Result<SessionConfig, String> {
    store::set_hash_key(&app, &hash_key)
}

/// Add or update a paired peer address.
/// `address` is the HTTP address for cross-device requests, e.g. "192.168.1.5:9876".
#[tauri::command]
pub fn add_paired_device(
    app: AppHandle,
    device_id: String,
    address: String,
    label: String,
) -> Result<SessionConfig, String> {
    store::upsert_peer(&app, PairedDevice { device_id, address, label })
}

/// Remove a paired peer by its device ID.
/// Also notifies the removed peer so it can remove us from its own list.
#[tauri::command]
pub fn remove_paired_device(app: AppHandle, device_id: String) -> Result<SessionConfig, String> {
    let cfg = store::bootstrap(&app);
    let peer = cfg.paired_devices.iter().find(|d| d.device_id == device_id).cloned();
    let hash_key = cfg.hash_key.clone();
    let my_device_id = cfg.device.device_id.clone();

    let result = store::remove_peer(&app, &device_id)?;
    crate::network::sse_subscriber::stop_subscriber(&device_id);

    // Fire-and-forget: tell the removed peer to drop us from its list too.
    if let Some(peer) = peer {
        tauri::async_runtime::spawn(async move {
            let client = reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(5))
                .build();
            if let Ok(client) = client {
                let _ = client
                    .post(format!("http://{}/unpair", peer.address))
                    .json(&serde_json::json!({ "key": hash_key, "device_id": my_device_id }))
                    .send()
                    .await;
            }
        });
    }

    Ok(result)
}

/// Set Ollama endpoint host and port.
#[tauri::command]
pub fn set_ollama_endpoint(app: AppHandle, host: String, port: u16) -> Result<SessionConfig, String> {
    store::set_ollama_endpoint(&app, &host, port)
}

/// Set the selected Ollama model. Pushed to paired peers in the background.
#[tauri::command]
pub fn set_ollama_model(app: AppHandle, model: String) -> Result<SessionConfig, String> {
    let cfg = store::set_ollama_model(&app, &model)?;
    let app_for_push = app.clone();
    let model_for_push = model.clone();
    tauri::async_runtime::spawn(async move {
        crate::network::sync::settings::push_ollama_model_to_all_peers(&app_for_push, &model_for_push).await;
    });
    crate::network::sse::broadcast(crate::network::sse::SyncEvent::SettingsChanged {
        field: "ollama_model".to_string(),
        value: serde_json::Value::String(model),
    });
    Ok(cfg)
}

/// Return available persona skill names (compiled + runtime user-created).
#[tauri::command]
pub fn list_personas(app: AppHandle) -> Vec<String> {
    let mut names: Vec<String> = crate::skills::persona_skill_names(&app);
    names.extend(crate::skills::list_runtime_persona_names(&app));
    names
}

/// Set selected persona by skill name. Pushed to paired peers in the background.
#[tauri::command]
pub fn set_persona(app: AppHandle, persona: String) -> Result<SessionConfig, String> {
    let cfg = store::set_persona(&app, &persona)?;
    let app_for_push = app.clone();
    let persona_for_push = persona.clone();
    tauri::async_runtime::spawn(async move {
        crate::network::sync::settings::push_persona_to_all_peers(&app_for_push, &persona_for_push).await;
    });
    crate::network::sse::broadcast(crate::network::sse::SyncEvent::SettingsChanged {
        field: "persona".to_string(),
        value: serde_json::Value::String(persona),
    });
    Ok(cfg)
}

/// Update PC control tool permissions. Pushed to paired peers in the background.
#[tauri::command]
pub fn set_pc_permissions(app: AppHandle, permissions: PcPermissions) -> Result<SessionConfig, String> {
    let cfg = store::set_pc_permissions(&app, permissions.clone())?;
    let app_for_push = app.clone();
    let perms_for_push = permissions.clone();
    tauri::async_runtime::spawn(async move {
        crate::network::sync::settings::push_pc_permissions_to_all_peers(&app_for_push, &perms_for_push).await;
    });
    let value = serde_json::to_value(&permissions).unwrap_or(serde_json::Value::Null);
    crate::network::sse::broadcast(crate::network::sse::SyncEvent::SettingsChanged {
        field: "pc_permissions".to_string(),
        value,
    });
    Ok(cfg)
}
