use tauri::AppHandle;

use super::store;
use super::types::{PairedDevice, SessionConfig};

/// Return the current session config (creates default on first run).
#[tauri::command]
pub fn get_session(app: AppHandle) -> Result<SessionConfig, String> {
    Ok(store::bootstrap(&app))
}

/// Set a human-readable label for this device (e.g. "My Phone").
#[tauri::command]
pub fn set_device_label(app: AppHandle, label: String) -> Result<SessionConfig, String> {
    store::set_label(&app, &label)
}

/// Set the session hash key directly.
/// Only accepts the 64-character hex key generated by the app.
#[tauri::command]
pub fn set_session_hash_key(app: AppHandle, hash_key: String) -> Result<SessionConfig, String> {
    store::set_hash_key(&app, &hash_key)
}

/// Add or update a paired peer address.
/// `address` is the HTTP address for cross-device requests, e.g. "192.168.1.5:9876".
#[tauri::command]
pub fn add_paired_device(
    app: AppHandle,
    device_id: String,
    address: String,
    label: String,
) -> Result<SessionConfig, String> {
    store::upsert_peer(&app, PairedDevice { device_id, address, label })
}

/// Remove a paired peer by its device ID.
/// Also notifies the removed peer so it can remove us from its own list.
#[tauri::command]
pub fn remove_paired_device(app: AppHandle, device_id: String) -> Result<SessionConfig, String> {
    let cfg = store::bootstrap(&app);
    let peer = cfg.paired_devices.iter().find(|d| d.device_id == device_id).cloned();
    let hash_key = cfg.hash_key.clone();
    let my_device_id = cfg.device.device_id.clone();

    let result = store::remove_peer(&app, &device_id)?;

    // Fire-and-forget: tell the removed peer to drop us from its list too.
    if let Some(peer) = peer {
        tauri::async_runtime::spawn(async move {
            let client = reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(5))
                .build();
            if let Ok(client) = client {
                let _ = client
                    .post(format!("http://{}/unpair", peer.address))
                    .json(&serde_json::json!({ "key": hash_key, "device_id": my_device_id }))
                    .send()
                    .await;
            }
        });
    }

    Ok(result)
}

/// Set Ollama endpoint host and port.
#[tauri::command]
pub fn set_ollama_endpoint(app: AppHandle, host: String, port: u16) -> Result<SessionConfig, String> {
    store::set_ollama_endpoint(&app, &host, port)
}

/// Return available persona skill names.
#[tauri::command]
pub fn list_personas() -> Vec<String> {
    crate::skills::persona_skill_names()
        .iter()
        .map(|s| (*s).to_string())
        .collect()
}

/// Set selected persona by skill name.
#[tauri::command]
pub fn set_persona(app: AppHandle, persona: String) -> Result<SessionConfig, String> {
    store::set_persona(&app, &persona)
}
