use serde::{Deserialize, Serialize};
use std::io::{BufRead, Write};
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};
use tauri::AppHandle;
use uuid::Uuid;
use crate::memory::memory_dir;

const POST_GEN_QUEUE_FILE: &str = "post_gen_queue.jsonl";
const RETENTION_DAYS: u64 = 7;

// ── State Enums ──────────────────────────────────────────────────────────────

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum PostGenState {
    /// Post text generated, waiting to be saved.
    PostGenerating,
    /// Post saved successfully to disk.
    PostCreated,
    /// Reactions (comments, likes) in progress.
    ReactionsInProgress,
    /// All steps completed successfully.
    Completed,
    /// Generation failed — see error field.
    Failed,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum CommentState {
    /// Comment text generated, waiting to be saved.
    Pending,
    /// Comment saved successfully.
    Created,
    /// Failed to generate or save.
    Failed,
}

// ── Data Structures ──────────────────────────────────────────────────────────

/// Tracks a single comment being generated for a post.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct CommentEntry {
    /// Character ID who should comment.
    pub character_id: String,
    /// Comment ID after it's saved (None until created).
    pub comment_id: Option<String>,
    /// Generated comment text.
    pub text: String,
    pub state: CommentState,
    pub error: Option<String>,
    /// Unix timestamp when this comment entry was created.
    pub created_at: u64,
}

/// Tracks a character's like/reaction on a post.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct LikeEntry {
    /// Character ID who liked.
    pub character_id: String,
    /// Like score (0-100).
    pub score: u8,
    /// Whether they actually liked it (probability).
    pub did_like: bool,
    /// Unix timestamp when this was generated.
    pub created_at: u64,
}

/// Tracks the entire post generation workflow.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PostGenEntry {
    /// Unique ID for this post generation task.
    pub id: String,
    /// Character who is posting.
    pub character_id: String,
    /// Post ID after it's created (None until created).
    pub post_id: Option<String>,
    /// The generated post text.
    pub generated_text: String,
    /// The generated timestamp (ISO 8601).
    pub generated_timestamp: String,
    /// Current state of this post generation.
    pub state: PostGenState,
    /// Comments being generated by other characters.
    pub comments: Vec<CommentEntry>,
    /// Like reactions from other characters.
    pub likes: Vec<LikeEntry>,
    /// Error message if state is Failed.
    pub error: Option<String>,
    /// Unix timestamp when this entry was created.
    pub created_at: u64,
    /// Unix timestamp when this entry was last updated.
    pub updated_at: u64,
}

impl PostGenEntry {
    /// Create a new post generation entry (initial state: PostGenerating).
    pub fn new(
        character_id: String,
        generated_text: String,
        generated_timestamp: String,
    ) -> Self {
        let now = current_timestamp();
        Self {
            id: Uuid::new_v4().to_string(),
            character_id,
            post_id: None,
            generated_text,
            generated_timestamp,
            state: PostGenState::PostGenerating,
            comments: Vec::new(),
            likes: Vec::new(),
            error: None,
            created_at: now,
            updated_at: now,
        }
    }

    /// Mark post as created with an ID.
    pub fn mark_post_created(&mut self, post_id: String) {
        self.post_id = Some(post_id);
        self.state = PostGenState::PostCreated;
        self.updated_at = current_timestamp();
    }

    /// Mark as completed.
    pub fn mark_completed(&mut self) {
        self.state = PostGenState::Completed;
        self.updated_at = current_timestamp();
    }

    /// Mark as failed.
    pub fn mark_failed(&mut self, error: String) {
        self.state = PostGenState::Failed;
        self.error = Some(error);
        self.updated_at = current_timestamp();
    }

    /// Start reactions phase.
    pub fn start_reactions(&mut self) {
        self.state = PostGenState::ReactionsInProgress;
        self.updated_at = current_timestamp();
    }

    /// Add a pending comment entry.
    pub fn add_comment(&mut self, character_id: String, text: String) {
        self.comments.push(CommentEntry {
            character_id,
            comment_id: None,
            text,
            state: CommentState::Pending,
            error: None,
            created_at: current_timestamp(),
        });
    }

    /// Mark a comment as created.
    pub fn mark_comment_created(&mut self, character_id: &str, comment_id: String) {
        if let Some(comment) = self.comments.iter_mut().find(|c| c.character_id == character_id) {
            comment.comment_id = Some(comment_id);
            comment.state = CommentState::Created;
            comment.created_at = current_timestamp();
        }
        self.updated_at = current_timestamp();
    }

    /// Mark a comment as failed.
    pub fn mark_comment_failed(&mut self, character_id: &str, error: String) {
        if let Some(comment) = self.comments.iter_mut().find(|c| c.character_id == character_id) {
            comment.state = CommentState::Failed;
            comment.error = Some(error);
            comment.created_at = current_timestamp();
        }
        self.updated_at = current_timestamp();
    }

    /// Check if all comments are in a terminal state (Created or Failed).
    #[allow(dead_code)]
    pub fn all_comments_done(&self) -> bool {
        self.comments.is_empty() || self.comments.iter().all(|c| c.state == CommentState::Created || c.state == CommentState::Failed)
    }

    /// Record a like/reaction from a character.
    pub fn add_like(&mut self, character_id: String, score: u8, did_like: bool) {
        self.likes.push(LikeEntry {
            character_id,
            score,
            did_like,
            created_at: current_timestamp(),
        });
        self.updated_at = current_timestamp();
    }

    /// Get total likes from tracked reactions.
    #[allow(dead_code)]
    pub fn get_like_count(&self) -> u32 {
        self.likes.iter().filter(|l| l.did_like).count() as u32
    }

    /// Check if this entry is old enough to be cleaned up (older than RETENTION_DAYS).
    pub fn is_stale(&self) -> bool {
        let age_seconds = current_timestamp() - self.created_at;
        age_seconds > (RETENTION_DAYS * 86400)
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn current_timestamp() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

fn queue_path(app: &AppHandle) -> PathBuf {
    memory_dir(app).join(POST_GEN_QUEUE_FILE)
}

// ── Load ─────────────────────────────────────────────────────────────────────

/// Load all post generation entries. Skips malformed lines silently.
pub fn load_all(app: &AppHandle) -> Vec<PostGenEntry> {
    let path = queue_path(app);
    let Ok(file) = std::fs::File::open(&path) else {
        return Vec::new();
    };
    std::io::BufReader::new(file)
        .lines()
        .filter_map(|l| l.ok())
        .filter(|l| !l.trim().is_empty())
        .filter_map(|l| serde_json::from_str::<PostGenEntry>(&l).ok())
        .collect()
}

/// Load only entries that are not yet completed.
pub fn load_pending(app: &AppHandle) -> Vec<PostGenEntry> {
    load_all(app)
        .into_iter()
        .filter(|e| e.state != PostGenState::Completed && e.state != PostGenState::Failed)
        .collect()
}

// ── Write ────────────────────────────────────────────────────────────────────

/// Rewrite the entire queue file (atomic via tmp file).
fn save_all(app: &AppHandle, entries: &[PostGenEntry]) -> Result<(), String> {
    let path = queue_path(app);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }

    let tmp = path.with_extension("jsonl.tmp");
    let file = std::fs::File::create(&tmp).map_err(|e| e.to_string())?;
    let mut writer = std::io::BufWriter::new(file);
    for entry in entries {
        let line = serde_json::to_string(entry).map_err(|e| e.to_string())?;
        writeln!(writer, "{line}").map_err(|e| e.to_string())?;
    }
    drop(writer);
    std::fs::rename(&tmp, &path).map_err(|e| e.to_string())
}

// ── Mutations ────────────────────────────────────────────────────────────────

/// Enqueue a new post generation task.
#[allow(dead_code)]
pub fn enqueue(
    app: &AppHandle,
    character_id: String,
    generated_text: String,
    generated_timestamp: String,
) -> Result<PostGenEntry, String> {
    let entry = PostGenEntry::new(character_id, generated_text, generated_timestamp);

    // Append to JSONL.
    let path = queue_path(app);
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let line = serde_json::to_string(&entry).map_err(|e| e.to_string())?;
    let mut file = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&path)
        .map_err(|e| e.to_string())?;
    writeln!(file, "{line}").map_err(|e| e.to_string())?;

    Ok(entry)
}

/// Save or update a single entry (creates if not found, updates if exists).
pub fn save_queue_entry(app: &AppHandle, updated: PostGenEntry) -> Result<(), String> {
    let mut all = load_all(app);
    if let Some(entry) = all.iter_mut().find(|e| e.id == updated.id) {
        *entry = updated;
    } else {
        all.push(updated);
    }
    save_all(app, &all)
}

/// Update a single entry in the queue (only if it already exists).
#[allow(dead_code)]
pub fn update_entry(app: &AppHandle, updated: PostGenEntry) -> Result<(), String> {
    let mut all = load_all(app);
    for entry in &mut all {
        if entry.id == updated.id {
            *entry = updated;
            break;
        }
    }
    save_all(app, &all)
}

/// Update multiple entries in one pass.
pub fn update_entries_batch(app: &AppHandle, updated: &[PostGenEntry]) -> Result<(), String> {
    let mut all = load_all(app);
    for entry in &mut all {
        if let Some(u) = updated.iter().find(|u| u.id == entry.id) {
            *entry = u.clone();
        }
    }
    save_all(app, &all)
}

/// Remove completed/failed entries older than RETENTION_DAYS.
pub fn cleanup_stale(app: &AppHandle) -> Result<u32, String> {
    let all = load_all(app);
    let original_count = all.len();

    let kept: Vec<PostGenEntry> = all
        .into_iter()
        .filter(|e| !e.is_stale())
        .collect();

    save_all(app, &kept)?;

    Ok((original_count - kept.len()) as u32)
}

/// Remove all entries for a specific character (useful for cleanup).
#[allow(dead_code)]
pub fn remove_character_entries(app: &AppHandle, character_id: &str) -> Result<(), String> {
    let all = load_all(app);
    let kept: Vec<PostGenEntry> = all
        .into_iter()
        .filter(|e| e.character_id != character_id)
        .collect();
    save_all(app, &kept)
}
